### ISSUE TITLE
delay for reduce code nesting

### ISSUE THREAD

**Issue by darkleaf** [Engelberg/better-cond#11]
```clojure
;; check-* return error map or nil

(defn process [params]
  (or (check-logged-out)
      (check-params params)
      (let [user (find-user params)]
        (or (check-authentication user params)
            (do (user-session/log-in! user)
                {:type ::processed :user user})))))

(defn process [params]
  (let [d-user (delay (find-user params))]
    (or (check-logged-out)
        (check-params params)
        (check-authentication @d-user params)
        (do (user-session/log-in! @d-user)
            {:type ::processed :user @d-user}))))

(b/defnc process [params]
  :let [err (or (check-logged-out)
                (check-params params))]
  (some? err) err
  :let [user (find-user params)
        err  (check-authentication user params)]
  (some? err) err
  :do (user-session/log-in! user)
  {:type ::processed :user user}))))))
```

I think that the example with delay more readable than the better-cond example.

Is it a good idea to use delay instead of better-cond?
Can you suggest examples when better-cond is better than delay?

**Comment by Engelberg** [comment]
I'm not convinced that delay is more readable. Does it effectively convey
that d-user will never be accessed if it is nil? No. By putting it up front
the you've told the reader nothing about the conditions under which the
delay is evaluated. Also it's awkward if you have a second variable
referring to the first. Also delay is less efficient. But your mileage may
vary.

On Mar 3, 2018 12:44 PM, "Mikhail Kuzmin" <notifications@github.com> wrote:

;; check-* return error map or nil

(defn process [params]
  (or (check-logged-out)
      (check-params params)
      (let [user (find-user params)]
        (or (check-authentication user params)
            (do (user-session/log-in! @d-user)
                {:type ::processed :user @d-user})))))

(defn process [params]
  (let [d-user (delay (find-user params))]
    (or (check-logged-out)
        (check-params params)
        (check-authentication @d-user params)
        (do (user-session/log-in! @d-user)
            {:type ::processed :user @d-user}))))

(b/defnc process [params]
  :let [err (or (check-logged-out)
                (check-params params))]
  (some? err) err
  :let [user (find-user params)
        err  (check-authentication user params)]
  (some? err) err
  :do (user-session/log-in! user)
  {:type ::processed :user @d-user}))))))

I think that the example with delay more readable than the better-cond
example.

Is it a good idea to use delay instead of better-cond?
Can you suggest examples when better-cond is better than delay?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Engelberg/better-cond/issues/11>, or mute the thread
