### ISSUE TITLE
::defn-args redefined

### ISSUE THREAD

**Issue by viebel** [Engelberg/better-cond#2]
Why did you copy the code from clojure `specs.clj` for definition of `::defn-args`

**Comment by Engelberg** [comment]
::arg-list and ::seq-binding-form don't unform properly, so I needed to fix those specs in my own namespace and then copy over everything that referred to them directly or indirectly to refer to the new, fixed specs instead.

**Comment by viebel** [comment]
Oh! I see.

Actually, I think that even with your code `unform` is not 100% accurate:

``` clojure
(s/unform ::arg-list (s/conform ::arg-list '[a b & c])) ; [a b (& c)]
```

**Comment by Engelberg** [comment]
Thank you for catching that.  It doesn't surprise me that there are some corner cases I didn't find.  Ultimately, I hope they fix this in core, but in the meantime, yes, this needs to be fixed.

If you see a way to fix this, I would welcome a pull request, otherwise I'll try to take a look at that scenario this weekend.

For the others, the key was to put (spec/conformer vec vec) in the right place (typically after the vector? but before the rest of the conforming logic in the `and`).  This may be a slightly different case since it is not about vector/list but about something getting wrapped in parens that shouldn't be, which may be from sub-use of spec.  This may require some questions to Alex Miller to resolve.

But if you figure out the solution, I would love to fix this.

**Comment by viebel** [comment]
I found a solution. See #3.

Not sure it's the best solution.

Also, I don't understand completely how `conformer` works: what does the 1st parameter do?
